on: [push, pull_request]
name: Tests and code
jobs:
  qa-code:
    name: "Check code quality"
    runs-on: ubuntu-latest
    steps:
      - uses: cristiroma/drupal-release-action@v1.3
        with:
          dev: true
          artifact: false

      - uses: cristiroma/drupal-code-qa-action@main
