####
# 1. Configure below the triggers when the checks are running
####

on: [push, pull_request]
name: 'Drupal instance testing'
jobs:
  qa-tests:
    name: 'Execute Drupal tests'
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: eaudeweb/drupal-install-action@main
        with:
          dev: true

      - name: Execute unit tests
        run: ./vendor/bin/phpunit --testsuite=unit

      - name: Execute kernel tests
        run: ./vendor/bin/phpunit --testsuite=kernel

      - name: 'Execute tests'
        uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

