on: [push, pull_request]
name: Tests and code
jobs:
  qa-tests:
    name: "Run Drupal tests"
    runs-on: ubuntu-latest
    needs: code
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: cristiroma/drupal-release-action@v1.3
        with:
          dev: true
          artifact: false

      - name: Execute tests
        run: |
          cp example.phpunit.xml phpunit.xml
          ./vendor/bin/phpunit web/modules/custom
