on: [push, pull_request]
name: "Run project tests"
jobs:
  qa-tests:
    name: "Run Drupal tests"
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: eaudeweb/drupal-install-action@main
        with:
          dev: true

      - name: 'Execute Unit tests'
        run: ./vendor/bin/phpunit --testsuite=unit

      - name: 'Execute Kernel tests'
        run: ./vendor/bin/phpunit --testsuite=kernel

      - name: 'Setup chromedriver'
        uses: nanasess/setup-chromedriver@v1
#        with:
#          # Optional: do not specify to match Chrome's version
#          chromedriver-version: '88.0.4324.96'

      - name: 'Execute Functional JavaScript tests'
        run: |
          export DISPLAY=:99
          chromedriver --verbose &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          ./vendor/bin/phpunit --testsuite=functionaljs
